int64_t SpiteArguments_count(SpiteArguments* self);
SpiteString* SpiteArguments_get(SpiteArguments* self, int64_t index);
SpiteString* SpiteArguments_lookup(SpiteArguments* self, const char* key);

void File_init(File* self);
File* File_allocate(void);
File* File_default(void);
File* File_make(SpiteString* path);
File* File_retain(File* self);
void File_release(File* self);
File* File_copy(File* self);
File* File_deep_copy(File* self);
void File_File(File* self, SpiteString* path);
SpiteString* File_read(File* self);
bool File_write(File* self, SpiteString* text);
bool File_append(File* self, SpiteString* text);
bool File_exists(File* self);
bool File_remove(File* self);
void Directory_init(Directory* self);
Directory* Directory_allocate(void);
Directory* Directory_default(void);
Directory* Directory_make(SpiteString* path);
Directory* Directory_retain(Directory* self);
void Directory_release(Directory* self);
Directory* Directory_copy(Directory* self);
Directory* Directory_deep_copy(Directory* self);
void Directory_Directory(Directory* self, SpiteString* path);
List_String* Directory_files(Directory* self);
List_String* Directory_folders(Directory* self);
bool Directory_exists(Directory* self);
bool Directory_create(Directory* self);
void Process_init(Process* self);
Process* Process_allocate(void);
Process* Process_default(void);
Process* Process_make(SpiteString* command, List_String* arguments);
Process* Process_retain(Process* self);
void Process_release(Process* self);
Process* Process_copy(Process* self);
Process* Process_deep_copy(Process* self);
void Process_Process(Process* self, SpiteString* command, List_String* arguments);
int32_t Process_run(Process* self);
SpiteString* Process_output(Process* self);
void Program_init(Program* self);
Program* Program_allocate(void);
Program* Program_default(void);
Program* Program_make(void);
Program* Program_retain(Program* self);
void Program_release(Program* self);
Program* Program_copy(Program* self);
Program* Program_deep_copy(Program* self);
void Program_exit(Program* self, int32_t code);
void Program_sleep(Program* self, int32_t milliseconds);
SpiteString* Program_environment(Program* self, SpiteString* name);
