int64_t SpiteArguments_count(SpiteArguments* self);
SpiteString* SpiteArguments_get(SpiteArguments* self, int64_t index);
SpiteString* SpiteArguments_lookup(SpiteArguments* self, const char* key);

void Directory_init(Directory* self);
Directory* Directory_allocate(void);
Directory* Directory_default(void);
Directory* Directory_make(SpiteString* path);
Directory* Directory_retain(Directory* self);
void Directory_release(Directory* self);
Directory* Directory_copy(Directory* self);
Directory* Directory_deep_copy(Directory* self);
void Directory_Directory(Directory* self, SpiteString* path);
List_String* Directory_files(Directory* self);
List_String* Directory_folders(Directory* self);
bool Directory_exists(Directory* self);
bool Directory_create(Directory* self);
void Process_init(Process* self);
Process* Process_allocate(void);
Process* Process_default(void);
Process* Process_make(SpiteString* command, List_String* arguments);
Process* Process_retain(Process* self);
void Process_release(Process* self);
Process* Process_copy(Process* self);
Process* Process_deep_copy(Process* self);
void Process_Process(Process* self, SpiteString* command, List_String* arguments);
int32_t Process_run(Process* self);
SpiteString* Process_output(Process* self);
void Program_init(Program* self);
Program* Program_allocate(void);
Program* Program_default(void);
Program* Program_make(void);
Program* Program_retain(Program* self);
void Program_release(Program* self);
Program* Program_copy(Program* self);
Program* Program_deep_copy(Program* self);
void Program_exit(Program* self, int32_t code);
void Program_sleep(Program* self, int32_t milliseconds);
SpiteString* Program_environment(Program* self, SpiteString* name);
int32_t Program_live_allocations(Program* self);
SpiteString* Program_platform(Program* self);
void Console_init(Console* self);
Console* Console_allocate(void);
Console* Console_default(void);
Console* Console_make(void);
Console* Console_retain(Console* self);
void Console_release(Console* self);
Console* Console_copy(Console* self);
Console* Console_deep_copy(Console* self);
SpiteString* Console_read_line(Console* self);
void DynamicLibrary_init(DynamicLibrary* self);
DynamicLibrary* DynamicLibrary_allocate(void);
DynamicLibrary* DynamicLibrary_default(void);
DynamicLibrary* DynamicLibrary_make(SpiteString* file_name);
DynamicLibrary* DynamicLibrary_retain(DynamicLibrary* self);
void DynamicLibrary_release(DynamicLibrary* self);
DynamicLibrary* DynamicLibrary_copy(DynamicLibrary* self);
DynamicLibrary* DynamicLibrary_deep_copy(DynamicLibrary* self);
void* DynamicLibrary_symbol(DynamicLibrary* self, const char* name, const char* wanted_by);
void Memory_init(Memory* self);
Memory* Memory_allocate(void);
Memory* Memory_default(void);
Memory* Memory_make(void);
Memory* Memory_retain(Memory* self);
void Memory_release(Memory* self);
Memory* Memory_copy(Memory* self);
Memory* Memory_deep_copy(Memory* self);
int64_t Memory_allocate_bytes(Memory* self, int64_t bytes);
int64_t Memory_resize(Memory* self, int64_t address, int64_t bytes);
void Memory_free(Memory* self, int64_t address);
uint8_t Memory_read_byte(Memory* self, int64_t address, int64_t offset);
int32_t Memory_read_int(Memory* self, int64_t address, int64_t offset);
int64_t Memory_read_long(Memory* self, int64_t address, int64_t offset);
double Memory_read_double(Memory* self, int64_t address, int64_t offset);
void Memory_write_byte(Memory* self, int64_t address, int64_t offset, uint8_t value);
void Memory_write_int(Memory* self, int64_t address, int64_t offset, int32_t value);
void Memory_write_long(Memory* self, int64_t address, int64_t offset, int64_t value);
void Memory_write_double(Memory* self, int64_t address, int64_t offset, double value);
void Memory_copy_bytes(Memory* self, int64_t from, int64_t to, int64_t bytes);
SpiteString* Memory_text(Memory* self, int64_t address, int64_t length);
