int64_t SpiteArguments_count(SpiteArguments* self);
SpiteString* SpiteArguments_get(SpiteArguments* self, int64_t index);
SpiteString* SpiteArguments_lookup(SpiteArguments* self, const char* key);

void DynamicLibrary_init(DynamicLibrary* self);
DynamicLibrary* DynamicLibrary_allocate(void);
DynamicLibrary* DynamicLibrary_default(void);
DynamicLibrary* DynamicLibrary_make(SpiteString* file_name);
DynamicLibrary* DynamicLibrary_retain(DynamicLibrary* self);
void DynamicLibrary_release(DynamicLibrary* self);
DynamicLibrary* DynamicLibrary_copy(DynamicLibrary* self);
DynamicLibrary* DynamicLibrary_deep_copy(DynamicLibrary* self);
void* DynamicLibrary_symbol(DynamicLibrary* self, const char* name, const char* wanted_by);
void Memory_init(Memory* self);
Memory* Memory_allocate(void);
Memory* Memory_default(void);
Memory* Memory_make(void);
Memory* Memory_retain(Memory* self);
void Memory_release(Memory* self);
Memory* Memory_copy(Memory* self);
Memory* Memory_deep_copy(Memory* self);
int64_t Memory_allocate_bytes(Memory* self, int64_t bytes);
int64_t Memory_resize(Memory* self, int64_t address, int64_t bytes);
void Memory_free(Memory* self, int64_t address);
uint8_t Memory_read_byte(Memory* self, int64_t address, int64_t offset);
int32_t Memory_read_int(Memory* self, int64_t address, int64_t offset);
int64_t Memory_read_long(Memory* self, int64_t address, int64_t offset);
double Memory_read_double(Memory* self, int64_t address, int64_t offset);
void Memory_write_byte(Memory* self, int64_t address, int64_t offset, uint8_t value);
void Memory_write_int(Memory* self, int64_t address, int64_t offset, int32_t value);
void Memory_write_long(Memory* self, int64_t address, int64_t offset, int64_t value);
void Memory_write_double(Memory* self, int64_t address, int64_t offset, double value);
void Memory_copy_bytes(Memory* self, int64_t from, int64_t to, int64_t bytes);
SpiteString* Memory_text(Memory* self, int64_t address, int64_t length);
int32_t Memory_live_allocations(Memory* self);
